//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T2.CLS.LoggerExtensions.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Logs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Logs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("T2.CLS.LoggerExtensions.Core.Properties.Logs", typeof(Logs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~GenericFileBuffer( path:&apos;{path}&apos;, readLimit: &apos;{readLimit}&apos;, memoryBufferLimit: &apos;{memoryBufferLimit}, fileBufferLimit: &apos;{fileBufferLimit}&apos;, flushTimeout: &apos;{flushTimeout}&apos;, resendTimeout: &apos;{resendTimeout}&apos;,  workerCount: &apos;{workerCount}&apos;, encoding: &apos;{encoding}&apos;.
        /// </summary>
        internal static string LEC00001 {
            get {
                return ResourceManager.GetString("LEC00001", resourceCulture);
            }
        }

        ///<summary>
        ///Checked WorkerCount value: {workerCount}
        ///</summary>
        internal static string LEC00002
        {
            get
            {
                return ResourceManager.GetString("LEC00002", resourceCulture);
            }
        }

        ///<summary>
        ///Checked path value: {value}
        ///</summary>
        internal static string LEC00003
        {
            get
            {
                return ResourceManager.GetString("LEC00003", resourceCulture);
            }
        }

        ///<summary>
        ///~FileBufferWorker(workerIndex: {workerIndex})
        ///</summary>
        internal static string LEC00004
        {
            get
            {
                return ResourceManager.GetString("LEC00004", resourceCulture);
            }
        }

        ///<summary>
        ///~GenericFileBuffer
        ///</summary>
        internal static string LEC00005
        {
            get
            {
                return ResourceManager.GetString("LEC00005", resourceCulture);
            }
        }

        ///<summary>
        ///InputParameter: path='{path}'
        ///</summary>
        internal static string LEC00006
        {
            get
            {
                return ResourceManager.GetString("LEC00006", resourceCulture);
            }
        }

        ///<summary>
        ///InputParameter: readLimit='{readLimit}'
        ///</summary>
        internal static string LEC00007
        {
            get
            {
                return ResourceManager.GetString("LEC00007", resourceCulture);
            }
        }

        ///<summary>
        ///InputParameter: memoryBufferLimit='{memoryBufferLimit}'
        ///</summary>
        internal static string LEC00008
        {
            get
            {
                return ResourceManager.GetString("LEC00008", resourceCulture);
            }
        }

        ///<summary>
        ///InputParameter: fileBufferLimit='{fileBufferLimit}'
        ///</summary>
        internal static string LEC00009
        {
            get
            {
                return ResourceManager.GetString("LEC00009", resourceCulture);
            }
        }

        ///<summary>
        ///InputParameter: flushTimeout='{flushTimeout}'
        ///</summary>
        internal static string LEC00010
        {
            get
            {
                return ResourceManager.GetString("LEC00010", resourceCulture);
            }
        }

        ///<summary>
        ///InputParameter: resendTimeout='{resendTimeout}'
        ///</summary>
        internal static string LEC00011
        {
            get
            {
                return ResourceManager.GetString("LEC00011", resourceCulture);
            }
        }

        ///<summary>
        ///InputParameter: workerCount='{workerCount}'
        ///</summary>
        internal static string LEC00012
        {
            get
            {
                return ResourceManager.GetString("LEC00012", resourceCulture);
            }
        }
    }
}
